# Generated by Django 3.2.5 on 2022-05-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
