# Generated by Django 3.2.5 on 2022-06-25 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0003_customlist_listitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customlist',
            name='list_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='einkaufsliste_app.listitem'),
        ),
    ]
