# Generated by Django 3.2.5 on 2022-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0005_auto_20220625_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'current weather'), (2, 'forecast weather')])),
                ('weather_id', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=140)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('clouds', models.PositiveSmallIntegerField()),
                ('weather_date', models.DateTimeField()),
                ('data_received_date', models.DateTimeField()),
            ],
        ),
    ]
