# Generated by Django 3.2.5 on 2022-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0006_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
