# Generated by Django 3.2.5 on 2022-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0007_wasteevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wasteevent',
            options={'ordering': ['event_date']},
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='probability_of_rain',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
