# Generated by Django 3.2.5 on 2022-10-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0008_auto_20220724_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'kilogram'), (2, 'pieces'), (3, 'gram'), (4, 'tablespoon'), (5, 'teaspoon'), (6, 'mililiter'), (7, '')], default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=140)),
                ('preparation', models.TextField()),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='einkaufsliste_app.ingredient')),
            ],
        ),
    ]
