# Generated by Django 3.2.5 on 2022-10-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0012_auto_20221010_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ingredients', to='einkaufsliste_app.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'kilogram'), (2, 'pieces'), (3, 'gram'), (4, 'tablespoon'), (5, 'teaspoon'), (6, 'mililiter'), (8, 'some'), (9, 'liter'), (10, 'packs'), (11, 'handfull'), (49, 'stem'), (13, 'knife tip'), (14, 'bunch'), (15, 'pinch'), (16, 'stick'), (17, 'can'), (18, 'cans'), (19, 'stems'), (20, 'slices'), (21, 'twigs'), (22, 'tubers'), (23, 'thick'), (24, 'splashes'), (25, 'leaves'), (26, 'cubes'), (27, 'twig'), (28, 'pack'), (29, 'plate'), (30, 'sticks'), (31, 'ball'), (32, 'box'), (33, 'sheets'), (34, 'packages'), (35, 'slice'), (36, 'glass'), (37, 'pinches'), (38, 'bag'), (39, 'small'), (77, 'smaller'), (41, 'panicle'), (42, 'head'), (43, 'pair'), (44, 'bed'), (45, 'clove'), (46, 'panicles'), (47, 'balls'), (48, 'leave'), (49, 'stem'), (50, 'pods'), (51, 'flakes'), (52, 'cup'), (53, 'great'), (54, 'cm'), (55, 'heads'), (56, 'bottle'), (57, 'long'), (58, 'young'), (59, 'sachets'), (60, 'pouch'), (61, 'lacing'), (62, 'medium sized'), (63, 'cooking bag'), (64, 'little tin'), (65, 'tuber'), (66, 'drop'), (67, 'm'), (68, 'ring'), (69, 'cups'), (70, 'package'), (71, 'drops'), (72, 'shrub'), (73, 'cloves'), (74, 'full'), (75, 'beds'), (76, 'rolls'), (77, 'smaller'), (78, 'cl'), (79, 'lean'), (80, 'jars'), (81, 'stripes'), (82, 'portion'), (83, 'mug'), (84, 'roll'), (85, 'blocks'), (86, 'shrubs'), (87, 'plates'), (88, 'herb bouquet'), (89, 'spikes'), (90, 'herbage bundle'), (91, 'hands full'), (92, 'bowls'), (93, 'potty'), (94, 'rings'), (7, '')], default=7),
        ),
    ]
