# Generated by Django 3.2.5 on 2022-11-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0014_auto_20221031_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
