# Generated by Django 4.2.2 on 2023-06-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0016_auto_20221109_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasingItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='purchasingitem',
            name='date_created',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'kg'), (2, 'Stück'), (3, 'g'), (4, 'Esslöffel'), (5, 'Teelöffel'), (6, 'ml'), (8, 'etwas'), (9, 'l'), (10, 'Packungen'), (11, 'handvoll'), (49, 'Stängel'), (13, 'Msp.'), (14, 'Bund'), (15, 'Prise'), (16, 'Stange'), (17, 'Dose'), (18, 'Dosen'), (19, 'Stiele'), (20, 'Scheiben'), (21, 'Zweige'), (22, 'Knollen'), (23, 'dick'), (24, 'Spritzer'), (25, 'Blätter'), (26, 'Würfel'), (27, 'Zweig'), (28, 'Packung'), (29, 'Platte'), (30, 'Stangen'), (31, 'Ball'), (32, 'Kästchen'), (33, 'Blätter'), (34, 'Päckchen'), (35, 'Scheibe'), (36, 'Glas'), (37, 'Prisen'), (38, 'Tüte'), (39, 'kleine'), (77, 'kleiner'), (41, 'Rispe'), (42, 'Kopf'), (43, 'paar'), (44, 'Beet'), (45, 'Zehe'), (46, 'Rispen'), (47, 'Bälle'), (48, 'Blatt'), (49, 'Stiel'), (50, 'Schoten'), (51, 'Plättchen'), (52, 'Becher'), (53, 'großer'), (54, 'cm'), (55, 'Köpfe'), (56, 'Flasche'), (57, 'lange'), (58, 'junge'), (59, 'Tütchen'), (60, 'Beutel'), (61, 'Schuss'), (62, 'mittelgroße'), (63, 'Kochbeutel'), (64, 'Döschen'), (65, 'Knolle'), (66, 'Tropfen'), (67, 'm'), (68, 'Ring'), (69, 'Becher'), (70, 'Packet'), (71, 'Tropfen'), (72, 'Staude'), (73, 'Zehen'), (74, 'voll'), (75, 'Beete'), (76, 'Rollen'), (77, 'kleinerer'), (78, 'cl'), (79, 'schlanke'), (80, 'Gläser'), (81, 'Streifen'), (82, 'Portion'), (83, 'Tasse'), (84, 'Rolle'), (85, 'Blöcke'), (86, 'Stauden'), (87, 'Platten'), (88, 'Kräutersträußchen'), (89, 'Zacken'), (90, 'Kräuterbund'), (91, 'Händevoll'), (92, 'Schalen'), (93, 'Töpfchen'), (94, 'Ringe'), (95, 'Förmchen'), (96, 'Fläschchen'), (97, 'Tafel'), (98, 'Dolden'), (99, 'Flaschen'), (100, 'Messerspitzen'), (101, 'Schälchen'), (102, 'Briefchen'), (103, 'Riegel'), (104, 'Töpfe'), (7, '')], default=7),
        ),
        migrations.CreateModel(
            name='BarCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(unique=True)),
                ('purchasing_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='einkaufsliste_app.purchasingitem')),
            ],
        ),
        migrations.AddField(
            model_name='purchasingitem',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='einkaufsliste_app.purchasingitemcategory'),
        ),
    ]
