# Generated by Django 4.2.2 on 2023-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einkaufsliste_app', '0017_purchasingitemcategory_purchasingitem_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasingitem',
            options={'ordering': ['category__priority']},
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feelslike',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='gust',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='humidity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='precip',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='uv',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_dir',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nord'), (2, 'Nord Nordost'), (3, 'Ost'), (4, 'Ost Südost'), (5, 'Süd'), (6, 'West Südwest'), (7, 'West'), (8, 'West Nordwest')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchasingitem',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
